name: CI-CD

on: 
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v4.2.1
        with:
          context: ./lib
          file: Dockerfile
          push: true
          tags: 
            fernandodias08/orderparser:latest
