name: CI-CD

on: 
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0
      - name: Rodar Gradle Test
        uses: actions/checkout@v4.0.0
        with:
          repository: actions/gradle/wrapper-action
          path: .github/actions/gradle
          ref: v4
      - name: Gradle Test
        run: |
          cd .github/actions/gradle
          chmod +x gradlew
          ./gradlew clean test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{secrets.DOCKERHUB_USR}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          file: Dockerfile
          push: true
          tags:
            fernandodias08/orderparser:${{github.run_number}}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Definindo o context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          images: fernandodias08/orderparser:${{github.run_number}}
          manifests:
            k8s/deployment.yaml


          
